### ISSUE TITLE
PhpSpec 4 compatibility

### ISSUE THREAD

**Issue by mark-gerarts** [fetzi/phpspec-matchers#10]
First of all, thanks for this nice set of matchers! Are there any plans of releasing a version that's compatible with PhpSpec 4? After browsing the code and reading PhpSpec's [upgrade section](http://www.phpspec.net/en/stable/manual/upgrading-to-phpspec-4.html#upgrading-for-extension-authors), it seems that only the method signatures have to be adjusted.

**Comment by jaylinski** [comment]
@fetzi I will upgrade the code-quality package to phpspec 4 in the next 1 to 3 months.

Would be nice if we could release a phpspec 4 compatible version of our matchers. I think it has to be a major release (v2.0.0).

**Comment by mark-gerarts** [comment]
Thanks for the swift response, I'll be looking forward to the release then!

**Comment by fetzi** [comment]
@mark-gerarts you can now update to v2.0.0!

**Comment by mark-gerarts** [comment]
Awesome! I'll be trying it out in the following days.
