### ISSUE TITLE
add beGreater and beLess matcher

### ISSUE THREAD

**Issue by fetzi** [fetzi/phpspec-matchers#4]
Add custom matchers for `beGreater`and `beLess`.

The matchers accept a numeric argument and check the argument against the subject.

**Comment by fetzi** [comment]
@jaylinski should the matchers be called like above or `beGreaterThan` and `beLessThan`?

**Comment by jaylinski** [comment]
@fetzi Can't decide... why not both?

https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Matcher/TypeMatcher.php#L24

**Comment by fetzi** [comment]
ok, I will implement both.

**Comment by pamil** [comment]
`$this->getNumber()->shouldBeGreater(5);` just looks wrong, I'm for `beGreaterThan` / `beLessThan` 👍

**Comment by fetzi** [comment]
I've implemented both, we could remove beGreater/beLess from the documentation.

**Comment by fetzi** [comment]
@pamil I have removed the reference in the readme.
